//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiProductos.Models
{
    using System;
    using System.Collections.Generic;
    using WebApiProductos.Entidades;

    public partial class Productos
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public Nullable<int> Marcaid { get; set; }
        public Nullable<int> Departamentoid { get; set; }
    
        public virtual Marcas Marcas { get; set; }
    }
}
